name: payever
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  desktop_webview_window: ^0.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  